# Generated by Django 5.0.1 on 2024-02-06 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group_activity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberauthentication",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="memberauthentication",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="AuthenticationLog",
        ),
    ]
