# Generated by Django 5.0.1 on 2024-02-07 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group_activity", "0002_memberauthentication_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authentication",
            name="end",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name="authentication",
            name="start",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
