# Generated by Django 5.0.1 on 2024-02-07 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group_activity", "0003_alter_authentication_end_alter_authentication_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authentication",
            name="end",
            field=models.CharField(
                default="00:00",
                max_length=5,
                validators=[django.core.validators.RegexValidator("^\\d{2}:\\d{2}$")],
                verbose_name="인증종료",
            ),
        ),
        migrations.AlterField(
            model_name="authentication",
            name="start",
            field=models.CharField(
                default="00:00",
                max_length=5,
                validators=[django.core.validators.RegexValidator("^\\d{2}:\\d{2}$")],
                verbose_name="인증시작",
            ),
        ),
        migrations.AlterField(
            model_name="memberauthentication",
            name="content",
            field=models.CharField(max_length=100, null=True, verbose_name="인증내용"),
        ),
        migrations.AlterField(
            model_name="memberauthentication",
            name="image",
            field=models.ImageField(
                null=True, upload_to="authentication_images/", verbose_name="인증사진"
            ),
        ),
    ]
