# Generated by Django 5.0.1 on 2024-01-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10)),
                ('parent_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goal_management.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('favor_offline', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(default=None, to='goal_management.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_management.tempuser')),
            ],
        ),
    ]
