# Generated by Django 5.0.1 on 2024-02-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_in_group',
            field=models.BooleanField(default=False),
        ),
    ]
