# Generated by Django 5.0.1 on 2024-01-30 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parent_tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='goal_management.tag'),
        ),
    ]
