# Generated by Django 5.0.2 on 2024-02-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goal_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('cert_required', models.BooleanField(default=False)),
                ('cert_detail', models.TextField(blank=True, default='', null=True)),
                ('penalty_value', models.PositiveIntegerField(default=0)),
                ('favor_offline', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('deposit', models.PositiveIntegerField(default=0)),
                ('duration', models.DurationField(default=None)),
                ('closing_date', models.DateTimeField(default=None, null=True)),
                ('penalty_bank', models.PositiveIntegerField(default=0)),
                ('activityTags', models.ManyToManyField(default=None, to='goal_management.activitytag')),
            ],
        ),
    ]
