# Generated by Django 5.0.1 on 2024-02-06 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goal_management", "0002_initial"),
        ("group_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="authentication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authenticationlog",
            name="authentication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_auth",
                to="group_management.authentication",
            ),
        ),
        migrations.AddField(
            model_name="authenticationlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_auth_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="memberauthentication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="activityTags",
            field=models.ManyToManyField(
                default=None, to="goal_management.activitytag"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="master",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="members",
            field=models.ManyToManyField(
                default=None, related_name="members", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="tags",
            field=models.ManyToManyField(default=None, to="goal_management.tag"),
        ),
        migrations.AddField(
            model_name="memberauthentication",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_room",
                to="group_management.room",
            ),
        ),
        migrations.AddField(
            model_name="authenticationlog",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_auth_room",
                to="group_management.room",
            ),
        ),
        migrations.AddField(
            model_name="authentication",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room",
                to="group_management.room",
            ),
        ),
    ]
