# Generated by Django 5.0.1 on 2024-02-05 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_management', '0002_goal_tags_goal_user_tag_parent_tag'),
        ('group_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='master',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(default=None, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(default=None, to='goal_management.tag'),
        ),
    ]
