# Generated by Django 5.0.1 on 2024-02-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_management', '0002_alter_room_cert_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='favor_offline',
            field=models.BooleanField(default=False),
        ),
    ]
