# Generated by Django 5.0.1 on 2024-02-06 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group_management", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authenticationlog",
            name="authentication",
        ),
        migrations.RemoveField(
            model_name="authenticationlog",
            name="room",
        ),
        migrations.RemoveField(
            model_name="authenticationlog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="memberauthentication",
            name="room",
        ),
        migrations.RemoveField(
            model_name="memberauthentication",
            name="user",
        ),
        migrations.DeleteModel(
            name="Authentication",
        ),
        migrations.DeleteModel(
            name="AuthenticationLog",
        ),
        migrations.DeleteModel(
            name="MemberAuthentication",
        ),
    ]
