# Generated by Django 5.0.1 on 2024-02-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group_management", "0005_authentication"),
    ]

    operations = [
        migrations.AddField(
            model_name="authentication",
            name="content",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="authentication",
            name="image",
            field=models.ImageField(null=True, upload_to="authentication_images/"),
        ),
    ]
