# Generated by Django 5.0.1 on 2024-02-05 00:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group_management", "0006_authentication_content_authentication_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authentication",
            name="content",
        ),
        migrations.RemoveField(
            model_name="authentication",
            name="image",
        ),
    ]
