# Generated by Django 5.0.1 on 2024-02-05 04:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "group_management",
            "0008_remove_authentication_is_auth_member_authentication",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="member_Authentication",
            new_name="MemberAuthentication",
        ),
    ]
