<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-03 01:02
=======
# Generated by Django 5.0.1 on 2024-02-01 04:53
>>>>>>> b7743f47ce7f53b65bf5d32b3dedc803e7f116a7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
<<<<<<< HEAD
        ("rooms", "0001_initial"),
=======
        ('rooms', '__first__'),
>>>>>>> b7743f47ce7f53b65bf5d32b3dedc803e7f116a7
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
<<<<<<< HEAD
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alarm_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_alarms",
                        to="rooms.room",
                    ),
                ),
                (
                    "alarm_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_alarms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_alarms', to='rooms.room')),
                ('alarm_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_alarms', to=settings.AUTH_USER_MODEL)),
>>>>>>> b7743f47ce7f53b65bf5d32b3dedc803e7f116a7
            ],
        ),
    ]
