# Generated by Django 5.0.1 on 2024-02-10 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alarm', '0001_initial'),
        ('goal_management', '0001_initial'),
        ('group_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='alarm_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_alarms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alarm',
            name='alarm_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_alarms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alarm',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='goal_management.goal'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='group_management.room'),
        ),
    ]
