# Generated by Django 5.0.1 on 2024-01-31 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alarm', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='alarm_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_alarms', to='rooms.room'),
        ),
    ]
