# Generated by Django 5.0.1 on 2024-02-04 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarm_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_alarms', to=settings.AUTH_USER_MODEL),
        ),
    ]
