# Generated by Django 5.0.1 on 2024-02-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0002_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fuel",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
