# Generated by Django 5.0.1 on 2024-02-01 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0002_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
