# Generated by Django 5.0.1 on 2024-02-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0003_user_fuel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fuel",
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
