# Generated by Django 5.0.1 on 2024-02-03 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0004_alter_user_fuel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fuel",
            field=models.IntegerField(
                blank=True,
                default=100,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
