# Generated by Django 5.0.1 on 2024-02-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='authentication_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='인증여부')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('rule', models.CharField(max_length=100)),
            ],
        ),
    ]
